=== Leighton070103/wsd/web/WEB-INF/bookings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd"
    xmlns="http://www.uts.edu.au/31284/wsd"
    elementFormDefault="qualified">
    <xs:element name="bookings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="booking" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"/>
                            <xs:element name="student_name" type="xs:string"/>
                            <xs:element name="student_email" type="xs:string"/>
                            <xs:element name="tutor_name" type="xs:string"/>
                            <xs:element name="tutor_email" type="xs:string"/>
                            <xs:element name="subject" type="xs:string"/>
                            <xs:element name="status" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Leighton070103/wsd/web/WEB-INF/bookings.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookings xmlns="http://www.uts.edu.au/31284/wsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.uts.edu.au/31284/wsd bookings.xsd">
    <booking>
        <id>1</id>
        <student_name>yichen</student_name>
        <student_email>123@gmail.com</student_email>
        <tutor_name>Ryan</tutor_name>
        <tutor_email>456@gmail.com</tutor_email>
        <subject>WSD</subject>
        <status>Active</status>
    </booking>
</bookings>
